apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rollouts-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/martysohio/argotesting.git # Replace with your Git repo
    targetRevision: HEAD
    path: rolloutui # Path to the directory containing rollout.yaml
  destination:
    server: http://cluster-argo1:8001
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true   