apiVersion: argoproj.io/v1alpha1 
kind: ApplicationSet 
metadata: 
  name: app-set-matrix-generator 
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/martysohio/argotesting.git
              revision: main
              directories:
                - path: apps/*
          - clusters:
              selector:
                matchLabels:
                  environment: prod

  template:
    metadata:
      name: "matrix-generator-{{ .path.basename }}-{{ .name }}"

    spec:
      project: default

      source:
        repoURL: https://github.com/martysohio/argotesting.git
        targetRevision: main
        path: "{{ .path.path }}"

      destination:
        server: "{{ .server }}"
        namespace: "{{ .name }}-matrix-generator-{{ .path.basename }}"

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true