apiVersion: batch/v1
kind: CronJob
metadata:
  name: alpine-sleeper
spec:
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: alpine
              image: alpine:3.20
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - |
                  echo "Job started at $(date)"
                  sleep 3000
                  echo "Job completed at $(date)"