apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  namespace: argocd
  annotations:
    link.argocd.argoproj.io/external-link: http://google.com
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  source:
    repoURL: https://github.com/martysohio/argotesting.git
    targetRevision: main
    path: basic-nginx
    directory:
      exclude: 'basic-nginx-app.yaml' # Prevents the app from syncing itself

  destination:
    # server: http://cluster-terraform:8001
    namespace: basic-nginx

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
