apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: image-crd
  namespace: argocd
  annotations:
    link.argocd.argoproj.io/external-link: http://google.com
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  source:
    repoURL: https://github.com/martysohio/argotesting.git
    targetRevision: main
    path: image-updater
    directory:
      exclude: 'image_crd-app.yaml' # Prevents the app from syncing itself

  destination:
    server: in-cluster


  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
